# application.yml
logging:
      level:
        com.testvue.testvue.mapper: DEBUG







mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  rabbitmq:
    password: 123
    host: 192.168.81.133
    port: 5672
    username: root

    virtual-host: /root
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
      direct:
        acknowledge-mode: auto
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 20
      thread-name-prefix: Job-Thread-






