# application.yml
logging:
      level:
        com.testvue.testvue.Mapper: DEBUG

        com:
          github:
            xiaoymin=DEBUG:

knife4j:
  enable: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  rabbitmq:
    password: 123
    host: 192.168.81.133
    port: 5672
    username: root

    virtual-host: /root
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
      direct:
        acknowledge-mode: auto


